### ISSUE TITLE
Running codes with undefined variable / functions shows unicode hex instead of the letter itself in the output console in Firefox

### ISSUE THREAD

**Issue by dhrubomoy** [ikrum/chokjs#12]
This is related to the potaka.io page. Not sure if this is the right place to open this issue.
But if we run code like following in the code editor:

```
দেখাও(কখগঘ);
```

in the output console we get this error:

```
রেফারেন্স ইরর: \u0995\u0996\u0997\u0998 ডিফাইন করা হয় নি
```

It would be better if the letters themselves are in the output. Like this:

```
রেফারেন্স ইরর: "কখগঘ" ডিফাইন করা হয় নি
```

It will be helpful if the line numbers, where the errors were encountered, are included.

EDIT: I am using **Firefox 48.0.2**. This issue does not occur with Chrome.

**Comment by ikrum** [comment]
thanks, minify changed this into unicode. it will be solved

**Comment by dhrubomoy** [comment]
Thanks. Noticed another thing. If reserved words are used, a syntax error is shown nicely and this issue doesn't occur. eg.

```
দেখাও(থামো);
```

shows following error:

```
সিনট্যাক্স ইরর: ১ নাম্বার লাইনে ভুল আছে। অপ্রত্যাশিত 'থ' পাওয়া গেছে।
```

**Comment by ikrum** [comment]
দেখাও(কখগঘ);

রেফারেন্স ইরর: "কখগঘ" ডিফাইন করা হয় নি

from my pc, can you please give me a screenshot?

**Comment by dhrubomoy** [comment]
Here's the screenshot. I'm using **firefox 48.0.2**. The issue does not occur with Chrome, just figured.

![untitled](https://cloud.githubusercontent.com/assets/12648587/17943826/0bc5e6ea-6a0b-11e6-977f-307de7c590af.png)

**Comment by ikrum** [comment]
thanks ! I was testing in chrome. I will fix it

**Comment by ikrum** [comment]
Thanks for rising the issue. It's solved
