### ISSUE TITLE
Demo doesn't work on safari

### ISSUE THREAD

**Issue by anikdas** [ikrum/chokjs#19]
So the website [potaka.io](potaka.io) does not work on safari.
<img width="1280" alt="screen shot 2016-08-29 at 8 49 51 pm" src="https://cloud.githubusercontent.com/assets/5252956/18056640/54743450-6e2a-11e6-91e7-e6c2bd9919c2.png">

**Comment by ikrum** [comment]
we are aware of that. Potaka is not compatible with IE and Safari, We will fix this soon. Meantime, Please consider chrome and firefox for writing Potaka code.

Thanks for rising the issue. :)

**Comment by ikrum** [comment]
@anikdas 
The problem is solved !
Thanks for raising the issue.
