### ISSUE TITLE
PEG.JS Grammar file not open sourced

### ISSUE THREAD

**Issue by aniruddha-adhikary** [ikrum/chokjs#2]
Hi @ikrum bhaiya,

Without the peg.js grammar file, open sourcing the project is pretty much meaningless. Would you please upload the grammar file? 👍

**Comment by ikrum** [comment]
like I described here http://potaka.io/docs?page=contribution PEG is not open source yet. I am adding and removing features very randomly. It will be open soon, The stable version will be released soon

**Comment by aniruddha-adhikary** [comment]
I see. Then looks like real contribution has to wait until the parser is open sourced!

**Comment by ikrum** [comment]
For people with the expertise like you, yes it is. But if you contribute the project with any ideas and fixes. It will be marked in official site, as well as you will push those feature on github too, at stable release. so some things are manual before stable release. 

you see the contribution page, Every contribution is honored on the official site.
