### ISSUE TITLE
Modulus division (%)  return float but cant get only round number

### ISSUE THREAD

**Issue by amarkotha366** [ikrum/chokjs#3]
দেখাও(১২৩.৪%১০ ); 
=>৩.৪০০০০০০০০০০০০০৫৭ 
  দেখাও(১২.৩৪%১০ );
=>২.৩৪ 

But Need Result AS 

 দেখাও(১২৩.৪%১০ ); 
=>৩
  দেখাও(১২.৩৪%১০ );
=>২

**Comment by ikrum** [comment]
Thanks for your feedback. We will add parseInt() method

**Comment by osmangoninahid** [comment]
Good feedback Thanks @githubhasib

**Comment by RobinHossain** [comment]
I think "Math.floor()" / "Math.round()" function would better works in that case. @ikrum 
Thank You

**Comment by ikrum** [comment]
Thanks for rising the issue. It's solved. use _পূর্ণসংখ্যা() to get round number.
