### ISSUE TITLE
The output function (দেখাও) auto trims the forward spaces

### ISSUE THREAD

**Issue by Safayar052** [ikrum/chokjs#8]
দেখাও("কেমন আছ সবাই??");
দেখাও("   কেমন আছ সবাই??");

Both calls return 

কেমন আছ সবাই??
কেমন আছ সবাই?? 

Is it a bug of the potaka.io editor or the potaka.io itself?

**Comment by ikrum** [comment]
Right now it's trimming the leading space. If it seems not right it will be fixed.  Everything here is for user testing. Thanks for your feedback

**Comment by Safayar052** [comment]
দেখাও(১ + "._______" + "___________আম," + " " + "জাম");
দেখাও(১ + "._______" + "________আম," + "জাম");
[Here underscores are spaces...]
Output:
১. আম, জাম
১. আম,জাম 

So, the space between আম and জাম is ok, but other spaces are trimmed. Even after the period, all spaces are gone. This behavior is inconsistent. The stable version should fix this issue.

**Comment by ikrum** [comment]
Thanks for rising the issue. It will be fixed

**Comment by ikrum** [comment]
Problem has been solved. :)
